* org-if

*org-if* is a simple system for developing /Choose Your Own Adventure/ style [[https://en.wikipedia.org/wiki/Interactive_fiction][interactive fiction]] (i.e. similar to [[http://twinery.org/][Twine]]) using [[https://www.gnu.org/software/emacs/][Emacs]] and [[http://orgmode.org/][Org mode]].

** Install 
   
*** Git

Install the [[https://git-scm.com/][git version control system]] if you do not already have it.

**** Windows XP/Vista/7/8

1. Download the [[https://git-scm.com/download/win][Windows version]] of *git*.

2. Run the file you downloaded to install *git* on your system.

**** OSX

1. Download the [[https://git-scm.com/download/mac][OSX version]] of *git*.

2. Run the file you downloaded to install *git* on your system.
   
**** Ubuntu/Mint/Debian
    
1. Open the *Terminal* application and run the following command.

   #+begin_src sh
   sudo apt-get install git
   #+end_src

2. That's all s/he wrote!
   
*** Emacs

If you do not already have a recent version of *Emacs* (i.e. 24.5 or later), install one for your system.
 
**** Windows XP/Vista/7/8

=NOTE:= You will need to install [[http://www.7-zip.org/a/7z920.exe][7-Zip]] to unpack /emacs-bin/.
     
1. Download [[http://sourceforge.net/projects/emacs-bin/files/latest/download][emacs-bin]].
   
2. Open the file in *7-Zip* and extract the file contents to a directory of your choice.

3. Open your file manager and navigate to the directory you chose in the previous step.

4. Open the =bin= subdirectory and run *addpm.exe* to add *Emacs* to the Start Menu.

5. You have now installed *Emacs* under Windows. Congratulations!
   
**** OSX

1. Download an [[http://emacsformacosx.com/][OSX version]] of *Emacs*.

2. Click on the file you just downloaded.
   
3. Drag the file /Emacs/ to your =Applications= folder.

4. You have now installed *Emacs* for OSX!
   
**** Ubuntu/Mint/Debian
     
1. Open the *Terminal* application and run the following command.

   #+begin_src sh
   sudo apt-get install emacs
   #+end_src

2. You have installed *Emacs* on Linux with a single command! Aren't you swell?

**** Other Systems

If you know enough to install and use them, you know enough to install *Emacs*.

*** org-if

**** package-install

Currently, no package repositories carry *org-if*. With hope that will soon change!

**** Manual
     
1. Open a console. This step differs depending on your system.

   - Windows: Open /Start->All Programs->Git->Git Bash/
   - OSX: Open *Terminal*; you can find it in =/Applications/Utilities/Terminal/=
   - Ubuntu: Open the *Terminal* application by pressing the *Ctrl*, *Alt*, and *T* keys at the same time.
     
2. Type the following commands into the console.

   #+begin_src sh
   git clone https://gitlab.com/elzair/org-if.git ~/org-if
   #+end_src

3. Open *Emacs*

4. Press the *Alt* and *X* keys at the same time. You Should now see =M-x= in the bottom-left corner of your *Emacs window*.
   
5. Type =ielm=; then press the *Enter* key.

6. Paste each line of the following text into the /*ielm*/ window. Press the *Enter* key to execute each line.
   
   *NOTE:* You can paste text into Emacs either by selecting /Edit->Paste/ in the top menu.

   #+begin_src elisp
   (defvar scripts-dir (expand-file-name "pkg-devel-scripts" "~"))
   (make-directory scripts-dir t)
   (defvar pkg-devel (expand-file-name "pkg-devel.el" scripts-dir))
   (url-copy-file "https://gitlab.com/snippets/7736/raw" pkg-devel)
   (load pkg-devel)
   (defvar org-if-code (file-name-as-directory (expand-file-name "org-if" "~")))
   (package-initialize)
   (pkg-devel-refresh org-if-code)
   (find-file user-init-file)
   #+end_src

7. Paste the following text into the file that just opened.

   #+begin_src elisp
   (package-initialize)
   (require 'org-if)
   #+end_src

8. Click on =File->Save= in the top menu to save the file.
   
9. Close and re-open *Emacs* to complete the installation.
   
10. Whew! That was a long process! I will add *org-if* to a package repository soon!

** Use

*** Start

These instructions will help you start your first *org-if* game.

1. Open *Emacs*.

2. Select /File->Open File.../ in the top menu.

3. Navigate to the directory where you downloaded the *org-if* code. It is called =~/org-if= above.
   
4. Open the file =examples/simple-game/index.org=.

5. You should now see an item in the top menu with the name /Org-IF/. Click on /Org-IF->Active./
   
6. You have now started your first *org-if* game. 

*** Play

Simply click on the underlined text to move between pages.

*** Pause

If you want to pause the game while saving your place, select /Org-IF->Save & Quit/ in the top menu.

*** Restore

1. Open any /.org/ file in the directory containing the game you want to resume.

2. Then select /Org-IF->Restore/ in the top menu.
   
** Develop

I will write more extensive documentation soon. In the meantime, look at the files in [[file:examples/simple-game/][examples/simple-game]] for how to create a simple *org-if* game. 
